// COMPONENT should be defined in the script_component.hpp and included BEFORE this hpp

#define MAINPREFIX z
#define PREFIX mars
#define QMODNAME "Mars"

#define MAJOR 1
#define MINOR 0
#define PATCHLVL 0
#define BUILD 0

#define VERSION MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR MAJOR,MINOR,PATCHLVL,BUILD

// MINIMAL required version for the Mod. Components can specify others..
#define REQUIRED_VERSION 1.56
#define REQUIRED_CBA_VERSION {2,3,1}

#define COLOR_ACCENT_DEFAULT_R 0.741
#define COLOR_ACCENT_DEFAULT_G 0.173
#define COLOR_ACCENT_DEFAULT_B 0.173
#define COLOR_ACCENT_DEFAULT_RGB COLOR_ACCENT_DEFAULT_R,COLOR_ACCENT_DEFAULT_G,COLOR_ACCENT_DEFAULT_B
#define COLOR_ACCENT_DEFAULT_RGBA COLOR_ACCENT_DEFAULT_R,COLOR_ACCENT_DEFAULT_G,COLOR_ACCENT_DEFAULT_B,1

#define COLOR_WEST_RGBA_ARR [0,0.3,0.6,1]
#define COLOR_WEST_RGB_ARR [0,0.3,0.6]
#define COLOR_WEST_RGBA {0,0.3,0.6,1}
#define COLOR_WEST_RGB {0,0.3,0.6}

#define COLOR_EAST_RGBA_ARR [0.5,0,0,1]
#define COLOR_EAST_RGB_ARR [0.5,0,0]
#define COLOR_EAST_RGBA {0.5,0,0,1}
#define COLOR_EAST_RGB {0.5,0,0}

#define COLOR_GUER_RGBA_ARR [0,0.5,0,1]
#define COLOR_GUER_RGB_ARR [0,0.5,0]
#define COLOR_GUER_RGBA {0,0.5,0,1}
#define COLOR_GUER_RGB {0,0.5,0}

#define COLOR_CIV_RGBA_ARR [0.4,0,0.5,1]
#define COLOR_CIV_RGB_ARR [0.4,0,0.5]
#define COLOR_CIV_RGBA {0.4,0,0.5,1}
#define COLOR_CIV_RGB {0.4,0,0.5}

#define COLOR_EMPTY_RGBA_ARR [0.698,0.6,0,1]
#define COLOR_EMPTY_RGB_ARR [0.698,0.6,0]
#define COLOR_EMPTY_RGBA {0.698,0.6,0,1}
#define COLOR_EMPTY_RGB {0.698,0.6,0}

#define SIDE_WEST 1
#define SIDE_EAST 0
#define SIDE_GUER 2
#define SIDE_CIV 3
#define SIDE_EMPTY -1
